name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  # Release version as specified in the tag with generated changelog to GitHub
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - run: bunx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  # Run tests
  test:
    if: github.repository == 'konradag/remoraid-internal'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - id: install-deps
        name: Install dependencies
        run: |
          bun install
      - id: test
        name: Run test
        run: |
          bun test
  # Publish private package to GitHub Packages
  publish-gpr:
    if: github.repository == 'konradag/remoraid-internal'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: https://npm.pkg.github.com/
      - id: manipulate
        name: Manipulate package.json's 'name', 'repository', and 'bugs' fields
        run: |
          jq --arg name "@konradag/remoraid-internal" --arg url "git+https://github.com/konradag/remoraid-internal.git" --arg bugs "https://github.com/konradag/remoraid-internal/issues" '.name=$name | .repository.url=$url | .bugs=$bugs' package.json > package.tmp && mv package.tmp package.json
      - run: bun install
      - run: bun publish --registry=https://npm.pkg.github.com
        env:
          NPM_CONFIG_TOKEN: ${{secrets.GITHUB_TOKEN}}
